spring:
  application:
    name: clog-api
    version: 0.0.1
  security:
    oauth2:
      client:
        registration:
          apple:
            client-name: APPLE
            client-id: ${APPLE_CLIENT_ID:com.supershy.climbinglog.dev}
            redirect-uri: "https://dev-api.climb-log.my/login/oauth2/code/apple"
            authorization-grant-type: authorization_code
            scope:
              - openid
              - name
        provider:
          kakao:
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
            user-info-uri: https://appleid.apple.com/auth/userinfo
            user-name-attribute: sub

decorator:
  datasource:
    p6spy:
      enable-logging: true

jwt:
  secret: ${JWT_SECRET:your-secret-key}
  access-token-expiration-millis: 3600000
  refresh-token-expiration-millis: 604800000

apple:
  team-id: ${APPLE_TEAM_ID:SUMATJC294}
  client-id: ${APPLE_CLIENT_ID:com.supershy.climbinglog.dev}
  key-id: ${APPLE_KEY_ID:2LCD3NVM7C}
  private-key: ${APPLE_PRIVATE_KEY:-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHNrrMRdZ8tqnHJ52\ncbwg/geX1Wj9NY96+wGaBv4bY++gCgYIKoZIzj0DAQehRANCAAT/XB7o6MlUvJNb\nlwVwoljgcPSlSXnN6TbWk3s+f9WBUp4SNDIKBcYmVE3uHgykvMN0ICLYLF5Zntzf\n7ojx67sL\n-----END PRIVATE KEY-----}
kakao :
  client-id: ${KAKAO_CLIENT_ID:bcd91f3c57fea5dcd79cb36287f3b714}

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
