server:
  shutdown: graceful

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: clog-api
    version: 0.0.1
  config:
    import:
      - classpath:/infrastructure/application.yml
  security:
    oauth2:
      client:
        registration:
          apple:
            client-name: APPLE
            client-id: ${APPLE_CLIENT_ID}
            redirect-uri: "https://dev-api.climb-log.my/login/oauth2/code/apple"
            authorization-grant-type: authorization_code
            scope:
              - openid
              - name
        provider:
          kakao:
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
            user-info-uri: https://appleid.apple.com/auth/userinfo
            user-name-attribute: sub

decorator:
  datasource:
    p6spy:
      enable-logging: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-millis: 86400000
  refresh-token-expiration-millis: 604800000

apple:
  team-id: ${APPLE_TEAM_ID}
  client-id: ${APPLE_CLIENT_ID}
  key-id: ${APPLE_KEY_ID}
  private-key: ${APPLE_PRIVATE_KEY}
kakao :
  client-id: ${KAKAO_CLIENT_ID}

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
      status:
        http-mapping:
          DOWN: 503
          OUT_OF_SERVICE: 503
          UNKNOWN: 200
          UP: 200
        order: DOWN, OUT_OF_SERVICE, UP, UNKNOWN
