server:
  port: 8081

  servlet:
    session:
      timeout: 60m

spring:
  mvc:
    hidden method:
      filter:
        enabled: true

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-millis: 3600000
  refresh-token-expiration-millis: 604800000

ncp:
  storage:
    access-key: ${STORAGE_ACCESS_KEY}
    secret-key: ${STORAGE_SECRET_KEY}
    end-point: ${STORAGE_END_POINT}
    bucket-name: ${STORAGE_BUCKET_NAME}
    region: ${STORAGE_REGION}