spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    database-type: mysql
    baseline-version: 1
    locations: classpath:infrastructure/db/migration
    encoding: UTF-8
    validate-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate

decorator:
  datasource:
    p6spy:
      enable-logging: false

ncp:
  storage:
    access-key: ${STORAGE_ACCESS_KEY}
    secret-key: ${STORAGE_SECRET_KEY}
    end-point: ${STORAGE_END_POINT}
    bucket-name: ${STORAGE_BUCKET_NAME}
    region: ${STORAGE_REGION}

kakao:
  map:
    rest-api-key: ${KAKAO_MAP_REST_API_KEY}
    local-search-base-url: ${KAKAO_MAP_LOCAL_SEARCH_BASE_URL}

thumbnail:
  crop:
    enabled: true

aws:
  s3:
    access-key: ${AWS_S3_ACCESS_KEY}
    secret-key: ${AWS_S3_SECRET_KEY}
    region: ap-northeast-2
    bucket-name: ${AWS_S3_BUCKET_NAME}
  cloudfront:
    domain: ${AWS_CLOUDFRONT_DOMAIN}
