configuration:
  property:
    name: CONSOLE_LOG
    value: "%d{yyyy-MM-dd HH:mm:ss}:%-4relative [%thread] %highlight(%5level) %magenta(%logger) - %msg%n"

  appender:
    - name: CONSOLE
      class: ch.qos.logback.core.ConsoleAppender
      encoder:
        pattern: ${CONSOLE_LOG}
        charset: utf8

  logger:
    - name: org.springframework
      level: INFO
    - name: org.hibernate.SQL
      level: DEBUG

  root:
    level: DEBUG
    appender-ref:
      - ref: CONSOLE
