name: "[DEV] Build and Deploy"

on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Build with Gradle (skip tests)
        run: ./gradlew :clog-api:build :clog-admin:build -x test

      - name: Build API Docker Image
        run: |
          docker build -f clog-api/Dockerfile -t ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_API_IMAGE }}:${{ github.ref_name }} .

      - name: Push API Docker Image
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_API_IMAGE }}:${{ github.ref_name }}

      - name: Build Admin Docker Image
        run: |
          docker build -f clog-admin/Dockerfile -t ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_ADMIN_IMAGE }}:${{ github.ref_name }} .

      - name: Push Admin Docker Image
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_ADMIN_IMAGE }}:${{ github.ref_name }}

      - name: Deploy on Remote Server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker compose -f /root/docker-compose.yml pull api
            docker compose -f /root/docker-compose.yml pull admin
            docker compose -f /root/docker-compose.yml up -d api admin
